In [1]:
1

1

In [5]:
import pandas as pd
import pathlib

csv_path = pathlib.Path(r'C:\Users\ASUS\OneDrive\Desktop\data scicne fayllar\bootcamp\data_bootcamp.xlsx')
df = pd.read_excel(csv_path)
df

,EmployeeID,İşçi,Seher,Sube,Vəzifə,IşəBaşlamaTarixi,Maaş,Status
0,101,Elvin,Bakı,HR,Menecer,2020-05-10 00:00:00,1500,Active
1,102,Aysel,Bakı,IT,Developer,2019-03-15 00:00:00,2200,Active
2,103,Rauf,Gəncə,Maliyyə,Mühasib,2023-01-20 00:00:00,1800,Active
3,104,Nigar,Sumqayıt,Satış,Satış Meneceri,2018-11-05 00:00:00,1700,Inactive
4,105,Vüqar,Bakı,IT,Developer,2022-11-07 00:00:00,2300,Active
5,106,Samir,Şəki,Satış,Satış Meneceri,2020-09-12 00:00:00,1600,Inactive
6,107,Leyla,Lənkəran,HR,HR Meneceri,2017-06-18 00:00:00,2000,Active
7,108,Elçin,Bakı,Maliyyə,Mühasib,12.20.2019,1900,Active
8,109,Ramin,Mingəçevir,IT,Developer,2021-05-08 00:00:00,2100,Active
9,110,Nicat,Bakı,IT,Satış Meneceri,2022-01-15 00:00:00,1650,Inactive

In [9]:
df[(df["Seher"]=="Lənkəran") &
   (df["Status"]=="Active")]["Maaş"].sum()

np.int64(2000)

In [6]:
    # saul 1
df[(df["Seher"]=="Bakı") & (df["Status"]=="Active")]["Maaş"].sum()

np.int64(7900)

In [46]:
  #sual 2
df[(df["Sube"]=="IT") &
    (df["Maaş"]>2000)]["Maaş"].sum()

np.int64(6600)

In [47]:
#saul 7
df[(df["Seher"]=="Bakı")
& (df["Status"]=="Active")]["Maaş"].count()

np.int64(4)

In [11]:
# sual 8
df[(df["Seher"]=="Gəncə") 
   & (df["Status"]=="Active")
   & (df["Vəzifə"]=="Mühasib")]["İşçi"].count()

np.int64(1)

In [52]:
# sual 9 
df[df["Sube"] == "IT"]["Maaş"].mean()
df.loc[df["Sube"] == "IT", "Maaş"].mean()

np.float64(2062.5)

In [53]:
# sual 10
df[(df["Seher"]=="Sumqayıt")&(df["Vəzifə"]=="Satış Meneceri")]["Maaş"].mean()

np.float64(1700.0)

In [12]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

In [18]:
import pandas as pd
import pathlib

csv_path = pathlib.Path(r'C:\Users\ASUS\OneDrive\Desktop\data scicne fayllar\bootcamp\Algerian_forest_fires_dataset.csv')
df = pd.read_csv(csv_path)
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,26,9,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
243,27,9,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
244,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
245,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
246,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire